### ISSUE TITLE
NameError: `mumidistance` not defined when running Parsnp 2.0.6 with divergent genomes

### ISSUE THREAD

**Issue by Rave-W** [marbl/parsnp#165]
Hello Parsnp team,

Thank you for developing and maintaining Parsnp! I encountered an issue while running Parsnp 2.0.6 on macOS when processing a dataset of E. coli genomes. The program stopped with a `NameError` for `mumidistance`. This error appears after several warnings indicating that some genomes are more divergent from the reference genome.

**Error output:**

```
10:53:45 - INFO - <<Parsnp started>>
10:53:46 - WARNING - File /P2.fasta is 1.26x longer than reference! 
10:53:47 - WARNING - File /P32.fasta is 1.37x longer than reference! 
10:53:47 - WARNING - File /P36.fasta is 1.37x longer than reference! 
10:53:48 - WARNING - File /P95.fasta is 1.85x longer than reference! 
10:53:49 - INFO - Setting the partition size to 62
10:53:49 - INFO - Running partitions...
10:53:49 - INFO - 0%|          | 0/4 [00:00<?, ?it/s]
11:56:09 - INFO - 25%|##5       | 1/4 [1:02:20<3:07:00, 3740.27s/it]
13:31:37 - INFO - 50%|#####     | 2/4 [2:37:47<2:43:38, 4909.14s/it]
19:55:23 - INFO - 75%|#######5  | 3/4 [9:01:33<3:39:41, 13181.65s/it]
19:55:23 - INFO - 75%|#######5  | 3/4 [9:01:33<3:00:31, 10831.19s/it]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/anaconda3/bin/parsnp", line 1149, in run_parsnp_aligner
    logger.critical("Set of recruited genomes are too divergent for parsnp, please reduce MUMi (%f) and relaunch\n"%(float(mumidistance)))
NameError: name 'mumidistance' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/parsnp", line 1697, in <module>
    for cl, rc in zip(chunk_labels, return_codes):
  File "/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
NameError: name 'mumidistance' is not defined

```

**Comment by bkille** [comment]
@Rave-W thanks for bringing this up! I've fixed it so that the error message is more clear and the crash is more graceful.

**Comment by Rave-W** [comment]
@bkille Thanks for your quick response. It works for me now!
Here is the command line I used `parsnp -g <reference_genbank> -d <genomes> -o <output_dir> -c -p <threads>`
